package entities;
// Generated 2018-10-24 20:03:10 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private String birthDay;
     private String username;
     private String machineName;
     private String timeStamp;

    public Client() {
    }

	
    public Client(String birthDay, String username, String machineName) {
        this.birthDay = birthDay;
        this.username = username;
        this.machineName = machineName;
    }
    public Client(String birthDay, String username, String machineName, String timeStamp) {
       this.birthDay = birthDay;
       this.username = username;
       this.machineName = machineName;
       this.timeStamp = timeStamp;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public String getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getMachineName() {
        return this.machineName;
    }
    
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }
    public String getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }




}


