package entities;
// Generated 2018-10-24 18:04:28 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private String firstName;
     private String lastName;
     private String birthDay;
     private String username;
     private String machineName;
     private String timeStamp;

    public Client() {
    }

	
    public Client(String firstName, String lastName, String birthDay, String username, String machineName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDay = birthDay;
        this.username = username;
        this.machineName = machineName;
    }
    public Client(String firstName, String lastName, String birthDay, String username, String machineName, String timeStamp) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.birthDay = birthDay;
       this.username = username;
       this.machineName = machineName;
       this.timeStamp = timeStamp;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getMachineName() {
        return this.machineName;
    }
    
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }
    public String getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }




}


