package entities;
// Generated 2018-10-23 15:07:03 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int idClient;
     private String machineName;
     private String timeStamp;
     private int birthDay;
     private String userName;

    public Client() {
    }

    public Client(int idClient, String machineName, String timeStamp, int birthDay, String userName) {
       this.idClient = idClient;
       this.machineName = machineName;
       this.timeStamp = timeStamp;
       this.birthDay = birthDay;
       this.userName = userName;
    }
   
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }
    public String getMachineName() {
        return this.machineName;
    }
    
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }
    public String getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }
    public int getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(int birthDay) {
        this.birthDay = birthDay;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }




}


